[package]
name = "crane-workspace-deps-repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prisma-fmt = { git = "https://github.com/prisma/prisma-engines" }
